baseURL = "https://www.perpetualtoday.cf"
home = "Home"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
title = "Perpetual Today"
[[menu.footer]]
URL = "about"
name = "Against \"Owl\" Odds"
weight = 1
[[menu.footer]]
URL = "browse"
name = "All Posts"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact Perpetual Today"
weight = 3
[[menu.footer]]
URL = "ethics"
name = "Code of Conduct"
weight = 4
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "browse"
name = "Browse"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[module.imports]]
path = "heroicons"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
layout = "1"
mainSections = ["post", "editorial"]
[params.brand]
logo = "/assets/brand/logo.png"
monochrome = "/assets/brand/logo.svg"
preloader = "/assets/brand/loader.svg"
wordmark = "/assets/brand/wordmark.png"
[params.contact]
address = "University of Perpetual Help-GMA Campus, General Mariano Alvarez, Cavite"
email = "perpetualtoday@gmail.com"
hashtag = "PerpetualTodayGMA"
messenger = "@PerpetualToday"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/glide/glide.core.min.css"
[[params.plugins.css]]
link = "plugins/glide/glide.core.theme.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/glide/glide.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
[params.publication]
author = "Perpetual Today"
copyright = "2020 Perpetual Today and the [University of Perpetual Help-GMA Campus](https://gma.uphsl.edu.ph)."
description = "We are Perpetual Today, the official publication of the University of Perpetual Help-GMA Campus Senior High School Department."
[params.search]
enable = true
[params.services]
disqusShortname = "perpetualtoday"
formAction = "https://docs.google.com/forms/d/e/1FAIpQLSdAOBqw_Yyyul5w3sQaiSgWjTPd1C8f-c22pnjrwTjESZgtxg/formResponse"
[[params.social]]
icon = "ti-facebook"
link = "https://fb.me/perpetualtoday"
title = "Facebook"
[[params.social]]
icon = "ti-instagram"
link = "https://instagr.am/perpetualtoday"
title = "Instagram"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
