# default config
baseURL = "https://perpetualtoday.netlify.app"
languageCode = "en-us"
title = "Perpetual Today"
theme = "parsa"
summaryLength = "10"
paginate = 6

home = "Home"

# Social Media sites
[[params.social]]
title = "Facebook"
icon = "ti-facebook"
link = "https://fb.me/perpetualtoday"

[[params.social]]
title = "Instagram"
icon = "ti-instagram"
link = "https://instagr.am/perpetualtoday"

# Main Navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Browse"
URL = "browse"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

# Footer Navigation - Quick Links
[[menu.footer]]
URL = "about"
name = "Against \"Owl\" Odds"
weight = 1

[[menu.footer]]
URL = "browse"
name = "All Posts"
weight = 2

[[menu.footer]]
URL = "contact"
name = "Contact Perpetual Today"
weight = 3

[[menu.footer]]
URL = "ethics"
name = "Code of Conduct"
weight = 4

# Settings
[params]
# Logo and wordmark
logo = "/assets/brand/logo.png"
wordmark = "/assets/brand/wordmark.svg"

# theme layout ( two layout is available, "1" and "2" )s
layout = "1"

# Meta data
author = "Perpetual Today"
description = "We are Perpetual Today, the official publication of the University of Perpetual Help-GMA Campus Senior High School Department."
copyright = "2020 Perpetual Today and the [University of Perpetual Help-GMA Campus](https://gma.uphsl.edu.ph)."

# Contact Info
messenger = "@PerpetualToday"
hashtag = "@PerpetualToday"
email = "exmaple@ymail.com"
address = "University of Perpetual Help-GMA Campus, General Mariano Alvarez, Cavite"

# 3rd-party Services
[params.services]
google_analitycs_id = "UA-156100338-1"
google_analytics = "UA-156100338-1"
disqusShortname = "perpetualtoday"

# Newsletter
[params.newsletter]
enable = true
title = "The Perpetual Today Diurnal"
description = "Subscribe to our newsletter and stay updated with the latest news in and out of the campus."

# Preloader
[params.preloader]
enable = true
preloader = "/assets/brand/loader.svg"

# Search Box in Navigation
[params.search]
enable = true

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
