baseURL = "https://perpetualtoday.netlify.com"
disqusShortname = "perpetualtoday"
languageCode = "en-US"
paginate = 4
summaryLength = "10"
theme = "liva"
title = "Perpetual Today"
[[menu.footer]]
URL = "about"
name = "Against \"Owl\" Odds"
weight = 1
[[menu.footer]]
URL = "post"
name = "All Posts"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact Perpetual Today"
weight = 3
[[menu.footer]]
URL = "ethics"
name = "Code of Conduct"
weight = 4
[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Perpetual Today"
copyright = "2020 Perpetual Today and the [University of Perpetual Help-GMA Campus](https://gma.uphsl.edu.ph)."
description = "We are Perpetual Today, the official publication of the University of Perpetual Help-GMA Campus Senior High School Department."
email = "perpetualtoday@gmail.com"
googleAnalitycsID = "UA-156100338-1"
keywords = "perpetual gma, perpetualtoday, perpetualgma, general mariano alvarez"
home = "Home"
instagram = "PerpetualTodayGMA"
location = "University of Perpetual Help-GMA Campus, General Mariano Alvarez, Cavite"
logo = "images/logo.png"
logoalt = "images/logo-text.png"
messenger = "PerpetualToday"
[params.newsletter]
content = "Subscribe to our newsletter and stay updated with the latest news in and out of the campus."
enable = true
title = "The Perpetual Today Diurnal"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = "/assets/brand/loader.svg"
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "https://fb.me/perpetualtoday"
title = "Facebook"
[[params.social]]
icon = "ti-instagram"
link = "https://instagr.am/perpetualtoday"
title = "Instagram"
