---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: directory
  path: content/post
  label: News Posts
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/students-voice
  label: Editorial Posts
  create: documents
  match: "**/*"
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Pages
- type: document
  path: content/about/_index.md
  label: About Perpetual Today
  match: "**/*"
- type: document
  path: content/ethics/_index.md
  label: Code of Conduct
  match: "**/*"
- type: document
  path: content/contact/_index.md
  label: Contact Perpetual Today
  match: "**/*"
- type: directory
  path: content/about
  label: About Perpetual Today
  create: documents
  match: "**/*"
  templates:
  - about-page
- type: directory
  path: content/ethics
  label: Code of Conduct
  create: documents
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact Perpetual Today
  create: all
  match: "**/*"
- type: heading
  label: Site Settings
- type: document
  path: config.toml
  label: Configuration
- type: document
  path: data/about.yml
  label: Perpetual Today Members
upload_dir: static/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
