---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Pages
- type: directory
  path: content/about
  label: About Perpetual Today
  create: all
  match: "**/*"
- type: directory
  path: content/ethics
  label: Code of Conduct
  create: documents
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact Perpetual Today
  create: all
  match: "**/*"
upload_dir: static/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
