---
label: Page Config
hide_body: true
fields:
- type: text
  name: title
  label: Site Name
  hidden: false
- type: text
  name: baseURL
  label: Website Address
  description: URL of website
- type: text
  name: languageCode
  label: languageCode
  hidden: true
- type: text
  name: summaryLength
  label: summaryLength
  hidden: true
- type: number
  name: paginate
  label: paginate
  hidden: true
- type: text
  name: home
  label: home
  hidden: true
- type: field_group
  name: params
  label: Main Settings
  fields:
  - type: field_group
    name: brand
    label: Brand Settings
    fields:
    - type: file
      name: logo
      label: Colored Logo
    - type: file
      name: monochrome
      label: Monochrome Logo
      description: "<strong>SVG is recommended.</strong>"
    - type: file
      name: wordmark
      label: Wordmark
    - type: file
      name: preloader
      label: Preloader
  - type: field_group_list
    name: social
    label: Social Media Pages
    fields:
    - type: text
      name: title
      label: Name
    - type: text
      name: icon
      label: Icon
      description: Icon <strong>always starts </strong>with 'ti-'
    - type: text
      name: link
      label: Link
  - type: field_group
    name: contact
    label: Contact Details
    fields:
    - type: text
      name: messenger
      label: Facebook Messenger
    - type: text
      name: hashtag
      label: Instagram Hashtag
    - type: text
      name: email
      label: E-mail
    - type: text
      name: address
      label: Address
  - type: text
    name: layout
    label: layout
    hidden: true
  - type: list
    name: mainSections
    label: mainSections
    hidden: true
  - type: field_group
    name: publication
    label: publication
    fields:
    - type: text
      name: author
      label: author
    - type: textarea
      name: description
      label: description
    - type: text
      name: copyright
      label: copyright
    hidden: true
  - type: field_group
    name: services
    label: services
    fields:
    - type: text
      name: disqusShortname
      label: disqusShortname
    - type: textarea
      name: formAction
      label: formAction
    hidden: true
  - type: field_group
    name: preloader
    label: Preloader
    fields:
    - type: boolean
      name: enable
      label: Enabled
  - type: field_group
    name: search
    label: search
    fields:
    - type: boolean
      name: enable
      label: enable
    hidden: true
  - type: field_group
    name: plugins
    label: plugins
    fields:
    - type: field_group_list
      name: css
      label: css
      fields:
      - type: text
        name: link
        label: link
      hidden: true
    - type: field_group_list
      name: js
      label: js
      fields:
      - type: text
        name: link
        label: link
    hidden: true
- type: field_group
  name: menu
  label: Menus
  fields:
  - type: field_group_list
    name: main
    label: Header
    fields:
    - type: text
      name: name
      label: Name
    - type: text
      name: URL
      label: URL
    - type: number
      name: weight
      label: Importance
  - type: field_group_list
    name: footer
    fields:
    - type: text
      name: URL
      label: URL
    - type: text
      name: name
      label: Name
    - type: number
      name: weight
      label: Importance
    label: Footer
- type: field_group
  name: outputs
  label: outputs
  fields:
  - type: list
    name: home
    label: home
  hidden: true
- type: field_group
  name: module
  label: module
  fields:
  - type: field_group_list
    name: imports
    label: imports
    fields:
    - type: text
      name: path
      label: path
  hidden: true
- type: field_group
  name: taxonomies
  label: taxonomies
  fields:
  - type: text
    name: category
    label: category
  - type: text
    name: tag
    label: tag
  - type: text
    name: author
    label: author
  hidden: true
pages:
- config.toml
